openapi: 3.0.0
info:
  title: MY API LIST ON SWAGGER
  description: This is my company API Documentation
  version: "1.0"
  contact:
    email: "jagriti@gmail.com"
  license:
    name: Apache 2.0
    url: "http://www.apache.org/liscences/LIS"


#Return Users From get request
paths:
  /employee:
    get:
     summary: Returns a string.
     description: Check String
     responses:
        200:    # status code
          description: Successul Response
          

#Returns a User
  /user:
    get:
      summary: Returns a list of users.
      description: People Who are already registered
      responses:
        200:    # status code
          description: Successul Response
          content:
            application/json:
              schema: 
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string

#Returns an array of Users
  /users:
    get:
      summary: Returns a list of users.
      description: People Who are already registered
      responses:
        200:    # status code
          description: Successul Response
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string


#Get Request with path id
  /users/{userId}:
    get:
      summary: Returns a user by ID.
      description: Returns the Specific User
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type : integer
            format: int64
      responses: 
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                example: {name: jagriti}


components:
  schemas:
    User:
      type: object
      required:
        - name
        - id
      properties:
        id:
          type: integer
        name:
          type: string
